### ISSUE TITLE
the resulting html page from running learn does not display test information

### ISSUE THREAD

**Issue by jonopens** [learn-co-curriculum/js-object-oriented-object-methods-lab#2]
To reproduce:
- clone down lab
- enter learn command from terminal
- note that only one test shows on html page
- note that text of test is not in a test format
![screen shot 2017-10-10 at 9 32 53 pm](https://user-images.githubusercontent.com/10333387/31418197-9f61e8d6-ae02-11e7-8cd2-3f8491821346.png)

**Comment by jonopens** [comment]
note: only occurs when index.js is empty - upon adding code, the tests show as expected.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
Thank you for your contribution. 💙
